title: Duc Pham
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Enthusiast
  <br><br>
  <a href="https://www.linkedin.com/in/duc-pham-35910975/">LinkedIn</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-80637114-1 # your Google Analytics tracking ID here
